server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: car-consumer

  main:


    allow-bean-definition-overriding: true 

  thymeleaf:
    cache: false
    enabled: true

feign:
  hystrix:
    enabled: false #禁用 熔断器
  httpclient:
    connection-timeout: 30000

